rebuild:
	NIX_PATH="home-manager/nixos=/home/ghuntley/code/infra/desktops/home-manager/nixos:nixpkgs=/home/ghuntley/code/infra/desktops/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels" nixos-rebuild switch
