{
  boot.initrd.network = {
    enable = true;
    ssh = {
      enable = true;
      # To prevent ssh from freaking out because a different host key is used,
      # a different port for dropbear is useful (assuming the same host has also a normal sshd running)
      port = 2222;
      # dropbear uses key format different from openssh; can be generated by using:
      # $ nix-shell -p dropbear --command "dropbearkey -t ecdsa -f /tmp/initrd-ssh-key"
      hostECDSAKey = /run/keys/initrd-ssh-key;
      # public ssh key used for login
      authorizedKeys = [ "ssh-rsa AAAA..." ];
    };
    # this will automatically load the zfs password prompt on login
    # and kill the other prompt so boot can continue
    postCommands = ''
      echo "zfs load-key -a; killall zfs" >> /root/.profile
    '';
  };
}
