# Copyright (c) 2020 Geoffrey Huntley <ghuntley@ghuntley.com>. All rights reserved.
# SPDX-License-Identifier: Proprietary

backend:
  name: github
  repo: ghuntley/depot
  branch: trunk

media_folder: "web/ghuntley.com/input/downloads"
public_folder: "/downloads"
collections:
  - name: "notes"
    label: "Notes"
    folder: "web/ghuntley.com/input/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "web/ghuntley.com/input/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "talks"
    label: "Talks"
    folder: "web/ghuntley.com/input/talks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Video", name: "video", widget: "text"}
      - {label: "Misc", name: "misc", widget: "markdown"}

  - name: "page"
    label: "Page"
    folder: "web/ghuntley.com/input"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
